import pandas as pd

IN_FLAGS_CSV = "themis_timeslot_flags_ops.csv"

try:
    df_flags_ops = pd.read_csv(IN_FLAGS_CSV)
    print(f"File '{IN_FLAGS_CSV}' loaded successfully.")
    print("First 5 rows of df_flags_ops:")
    display(df_flags_ops.head())
except FileNotFoundError:
    print(f"[ERROR] File '{IN_FLAGS_CSV}' not found. Please ensure it has been generated by the previous step.")
    df_flags_ops = pd.DataFrame() # Initialize an empty DataFrame to prevent errors in subsequent cells
except Exception as e:
    print(f"[ERROR] An error occurred while loading the file: {e}")
    df_flags_ops = pd.DataFrame() # Initialize an empty DataFrame

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

# Ensure TIMES and target_grid_size are available
if 'TIMES' not in globals():
    TIMES = ["5_30AM","7_00AM","6_30PM","7_00PM"]
if 'target_grid_size' not in globals():
    target_grid_size = 100

def plot_operational_zones(grid_data, out_png, title):
    # Define colormap and normalization for the categories
    # 0: Bad, 1: Good Soft Only, 2: Good Strict
    colors = ['#FF4C4C', '#FFD700', '#6FC276'] # Red, Gold, Green
    cmap = mcolors.ListedColormap(colors)
    bounds = [-0.5, 0.5, 1.5, 2.5]
    norm = mcolors.BoundaryNorm(bounds, cmap.N)

    plt.figure(figsize=(10, 8), dpi=140)
    im = plt.imshow(grid_data, cmap=cmap, norm=norm, origin="upper", extent=[0, target_grid_size, target_grid_size, 0])

    plt.title(title)
    plt.xlabel('Grid Column')
    plt.ylabel('Grid Row')

    plt.xticks(np.arange(0, target_grid_size + 1, 10))
    plt.yticks(np.arange(0, target_grid_size + 1, 10))
    plt.gca().set_xticks(np.arange(0.5, target_grid_size, 1), minor=True)
    plt.gca().set_yticks(np.arange(0.5, target_grid_size, 1), minor=True)
    plt.grid(which='minor', color='w', linestyle='-', linewidth=0.5)
    plt.grid(which='major', color='k', linestyle='-', linewidth=1)

    # Create a custom colorbar with labels
    cbar = plt.colorbar(im, ax=plt.gca(), ticks=[0, 1, 2], fraction=0.046, pad=0.04)
    cbar.set_ticklabels(['Bad', 'Good Soft', 'Good Strict'])
    cbar.set_label('Operational Zone Status')

    plt.tight_layout()
    plt.savefig(out_png, dpi=200)
    plt.close()
    print("PNG:", out_png)

# Ensure df_flags_ops is loaded
if 'df_flags_ops' not in globals() or df_flags_ops.empty:
    print("[ERROR] df_flags_ops is not loaded or is empty. Please ensure the previous step ran successfully.")
else:
    print("\n--- Generating Operational Zone Maps ---")
    for t in TIMES:
        good_strict_col = f"SLOT_GOOD_strict_{t}"
        good_soft_col = f"SLOT_GOOD_soft_{t}"

        if good_strict_col in df_flags_ops.columns and good_soft_col in df_flags_ops.columns:
            # Categorize each cell
            operational_status = np.zeros(len(df_flags_ops), dtype=int) # Default to Bad (0)

            # Good Soft Only (1)
            operational_status[(~df_flags_ops[good_strict_col]) & (df_flags_ops[good_soft_col])] = 1
            # Good Strict (2)
            operational_status[df_flags_ops[good_strict_col]] = 2

            # Reshape to 100x100 grid
            grid_data = operational_status.reshape(target_grid_size, target_grid_size)

            # Generate plot
            out_png = f"/content/themis_OperationalZones_{t}.png"
            title = f"Operational Zones at {t.replace('_', ':').replace('AM', ' AM').replace('PM', ' PM')}"
            plot_operational_zones(grid_data, out_png, title)
        else:
            print(f"[WARN] Missing columns for fascia {t}: {good_strict_col} or {good_soft_col}")

    print("Operational zone map generation completed.")

from IPython.display import Image, display

TIMES = ["5_30AM", "7_00AM", "6_30PM", "7_00PM"]

for t in TIMES:
    time_str = t.replace('_', ':').replace('AM', ' AM').replace('PM', ' PM')
    png_path = f"/content/themis_OperationalZones_{t}.png"
    print(f"Mappa delle Zone Operative per {time_str}:")
    display(Image(filename=png_path))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Ensure df_flags_ops is loaded and TIMES are defined
# This assumes df_flags_ops was loaded in a previous cell, e.g., 'c44c8f2f'
if 'df_flags_ops' not in globals() or df_flags_ops.empty:
    print("[ERROR] df_flags_ops non è caricato o è vuoto. Assicurati che i passaggi precedenti siano stati eseguiti correttamente.")
    # Fallback to load if not available (for independent cell execution)
    try:
        IN_FLAGS_CSV = "themis_timeslot_flags_ops.csv"
        df_flags_ops = pd.read_csv(IN_FLAGS_CSV)
        TIMES = ["5_30AM","7_00AM","6_30PM","7_00PM"]
    except FileNotFoundError:
        print("[ERROR] Fallback: themis_timeslot_flags_ops.csv non trovato.")
        exit()

TIMES = ["5_30AM","7_00AM","6_30PM","7_00PM"]

plot_data = []

for t in TIMES:
    good_strict_col = f"SLOT_GOOD_strict_{t}"
    good_soft_col = f"SLOT_GOOD_soft_{t}"

    if good_strict_col in df_flags_ops.columns and good_soft_col in df_flags_ops.columns:
        operational_status = np.zeros(len(df_flags_ops), dtype=int) # Default to Bad (0)

        # Good Soft Only (1): Good Soft is True AND Good Strict is False
        operational_status[(~df_flags_ops[good_strict_col]) & (df_flags_ops[good_soft_col])] = 1
        # Good Strict (2): Good Strict is True
        operational_status[df_flags_ops[good_strict_col]] = 2

        # Count occurrences of each category
        counts = pd.Series(operational_status).value_counts().sort_index()

        # Add to plot_data, ensuring all categories (0, 1, 2) are present even if count is 0
        categories_map = {0: 'Bad', 1: 'Good Soft', 2: 'Good Strict'}
        for val, category_name in categories_map.items():
            count_val = counts.get(val, 0) # Use .get() to return 0 if category not found
            plot_data.append({'Fascia': t, 'Category': category_name, 'X_Value': val, 'Count': count_val})
    else:
        print(f"[WARN] Colonne mancanti per la fascia {t}: {good_strict_col} o {good_soft_col}")

if plot_data:
    df_plot = pd.DataFrame(plot_data)

    # Rename 'Fascia' column for English legend title
    df_plot.rename(columns={'Fascia': 'Time Slot'}, inplace=True)

    plt.figure(figsize=(12, 7), dpi=140)

    # Changed to a grouped bar plot for better visibility of discrete categories
    sns.barplot(data=df_plot, x='Category', y='Count', hue='Time Slot', palette='Dark2')

    plt.title('Distribution of Operational Zones (100x100 Grid)') # Translated title
    plt.xlabel('Operational Zone Category') # Translated x-label
    plt.ylabel('Number of Pixels') # Translated y-label

    # Rotate x-axis labels if needed for better readability
    plt.xticks(rotation=15, ha='right')

    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()

    out_png = '/content/themis_OperationalZoneDistribution.png'
    plt.savefig(out_png, dpi=200)
    plt.close()
    print(f"PNG saved to: {out_png}") # Translated output message
else:
    print("No data available to generate the plot.") # Translated error message

from IPython.display import Image, display

output_png = '/content/themis_OperationalZoneDistribution.png'
print("Visualizzazione della distribuzione delle zone operative:")
display(Image(filename=output_png))
